name: team4_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas>=1.3
    - numpy>=1.21
    - matplotlib>=3.4
    - seaborn>=0.11
    - scikit-learn>=1.0
    - scipy>=1.7
    - lightgbm>=3.3
    - xgboost>=1.5
    - openpyxl
    - jupyter
    - notebook
    - ipykernel
